name: HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'upload-files'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'myfolder'
        destination: 'cooding-frontend/'
        parent: false
