name: HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Upload:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'upload-files'
      uses: 'google-github-actions/upload-cloud-storage@main'
      with:
        path: '../landing'
        destination: 'cooding-io'
        parent: false
